# Generated by Django 4.1.5 on 2023-02-01 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShortURL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_url", models.URLField(max_length=500)),
                ("short_code", models.CharField(max_length=20, unique=True)),
                ("short_url", models.CharField(max_length=200, unique=True)),
            ],
        ),
    ]
